### ISSUE TITLE
deployment guide link broken

### ISSUE THREAD

**Issue by mitchvandyken** [aws-quickstart/quickstart-nvidia-cloudxr#46]
The deployment guide link on the main page is broken. Here is a link: https://aws-quickstart.github.io/quickstart-nvidia-cloudxr/

**Comment by davmayd** [comment]
The guide is awaiting vetting by technical writers and legal review before it can be made public. In the meantime, you can fork the repo, clone it locally, update the boilerplate module in the `doc-edits` branch, and run `docs/boilerplate/.utils/build_docs.sh` to generate a local copy
